In [1]:
cd ..

/Users/pardhu/Developer/TMF Classfier

In [2]:
import pandas as pd
import re
from transformers import AutoTokenizer
from tqdm import tqdm

[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

In [3]:
df = pd.read_csv("raw_extracted_dataset.csv")

print(df.shape)
df.head()

(53, 4)

,file_name,class,text,num_chars
0,Prot_008.pdf,protocol,Clinical Study Protocol \nDrug Substance Durva...,271411
1,Prot_009.pdf,protocol,Official Protocol Title: \nNCT number: \nNCT03...,358803
2,Prot_007.pdf,protocol,Official Protocol Title:\nNCT number:\nDocumen...,187601
3,Prot_013.pdf,protocol,PF-06863135 (Elranatamab)\nProtocol C1071003\n...,342031
4,Prot_012.pdf,protocol,"This may include, but is not limited to, redac...",212928

In [4]:
def clean_text(text):

    text = str(text)

    # remove extra spaces/newlines
    text = re.sub(r"\s+", " ", text)

    # remove weird characters
    text = re.sub(r"[^\x00-\x7F]+", " ", text)

    # remove multiple spaces
    text = re.sub(r" +", " ", text)

    return text.strip()

In [5]:
df["clean_text"] = df["text"].apply(clean_text)

df[["class", "clean_text"]].head()

      class                                         clean_text
0  protocol  Clinical Study Protocol Drug Substance Durvalu...
1  protocol  Official Protocol Title: NCT number: NCT033022...
2  protocol  Official Protocol Title: NCT number: Document ...
3  protocol  PF-06863135 (Elranatamab) Protocol C1071003 Fi...
4  protocol  This may include, but is not limited to, redac...

In [6]:
MODEL_NAME = "emilyalsentzer/Bio_ClinicalBERT"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [7]:
def chunk_text(text,
               tokenizer,
               max_tokens=512,
               overlap=50):

    tokens = tokenizer.encode(
        text,
        add_special_tokens=False
    )

    chunks = []

    start = 0

    while start < len(tokens):

        end = start + max_tokens

        chunk_tokens = tokens[start:end]

        chunk = tokenizer.decode(
            chunk_tokens,
            skip_special_tokens=True
        )

        chunks.append(chunk)

        start += (max_tokens - overlap)

    return chunks

In [8]:
chunk_dataset = []

for _, row in tqdm(df.iterrows(),
                   total=len(df)):

    chunks = chunk_text(
        row["clean_text"],
        tokenizer
    )

    for idx, chunk in enumerate(chunks):

        chunk_dataset.append({

            "file_name": row["file_name"],

            "class": row["class"],

            "chunk_id": idx,

            "chunk_text": chunk,

            "chunk_chars": len(chunk)

        })

100%|██████████| 53/53 [00:13<00:00,  3.94it/s]

In [9]:
chunk_df = pd.DataFrame(chunk_dataset)

print(chunk_df.shape)

chunk_df.head()

(4078, 5)

,file_name,class,chunk_id,chunk_text,chunk_chars
0,Prot_008.pdf,protocol,0,clinical study protocol drug substance durvalu...,1807
1,Prot_008.pdf,protocol,1,"1. 0, 05 - jun - 2017 name of authorized perso...",1877
2,Prot_008.pdf,protocol,2,lymphocyte subsets within the tumor microenvir...,2206
3,Prot_008.pdf,protocol,3,"on days - 1 & 1 and of cycle 1, and then on da...",1983
4,Prot_008.pdf,protocol,4,2 will clinical study protocol drug substance ...,2309

In [10]:
chunk_df = pd.DataFrame(chunk_dataset)

print(chunk_df.shape)

chunk_df.head()

(4078, 5)

,file_name,class,chunk_id,chunk_text,chunk_chars
0,Prot_008.pdf,protocol,0,clinical study protocol drug substance durvalu...,1807
1,Prot_008.pdf,protocol,1,"1. 0, 05 - jun - 2017 name of authorized perso...",1877
2,Prot_008.pdf,protocol,2,lymphocyte subsets within the tumor microenvir...,2206
3,Prot_008.pdf,protocol,3,"on days - 1 & 1 and of cycle 1, and then on da...",1983
4,Prot_008.pdf,protocol,4,2 will clinical study protocol drug substance ...,2309

In [11]:
chunk_df_v1 = chunk_df[
    chunk_df["class"] != "informed_consent"
].reset_index(drop=True)

chunk_df_v1["class"].value_counts()

class
protocol                     1986
statistical_analysis_plan    1335
safety_report                 706
Name: count, dtype: int64

In [12]:
target_per_class = 700

balanced_chunk_df = (
    chunk_df_v1
    .groupby("class", group_keys=False)
    .apply(
        lambda x: x.sample(
            n=min(len(x), target_per_class),
            random_state=42
        )
    )
    .reset_index(drop=True)
)

balanced_chunk_df["class"].value_counts()

/var/folders/fn/knzvwqfx529d_ynxfzrct8f80000gn/T/ipykernel_15575/251611839.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(

class
protocol                     700
safety_report                700
statistical_analysis_plan    700
Name: count, dtype: int64

In [13]:
balanced_chunk_df.groupby("class").agg(
    total_chunks=("chunk_text", "count"),
    avg_chunk_chars=("chunk_chars", "mean"),
    min_chunk_chars=("chunk_chars", "min"),
    max_chunk_chars=("chunk_chars", "max")
)

,total_chunks,avg_chunk_chars,min_chunk_chars,max_chunk_chars
class,,,,
protocol,700,1913.488571,272,2966
safety_report,700,2203.084286,314,2926
statistical_analysis_plan,700,1812.327143,26,2872

In [14]:
for i in range(5):

    print("=" * 100)

    print("CLASS:",
          balanced_chunk_df.iloc[i]["class"])

    print("CHUNK ID:",
          balanced_chunk_df.iloc[i]["chunk_id"])

    print("=" * 100)

    print(
        balanced_chunk_df.iloc[i]["chunk_text"][:2000]
    )

    print("\n\n")

====================================================================================================
CLASS: protocol
CHUNK ID: 54
====================================================================================================
pd - l2 ). based on preclinical in vitro data, pembrolizumab has high affinity and potent receptor blocking activity for pd - 1. pembrolizumab has an acceptable preclinical safety profile and is in clinical development as an iv immunotherapy for advanced malignancies. keytruda ( pembrolizumab ) is indicated for the treatment of patients across a number of indications. for more details on specific indications, refer to the ib. refer to the ib / approved labeling for detailed background information on mk - 3475. 05nqkr 06dzns product : mk - 3475 23 protocol / amendment no. : 598 - 06 mk - 3475 - 598 - 06 final protocol 11 - dec - 2020 confidential pharmaceutical and therapeutic background the importance of intact immune surveillance in controlling outgrowth of neoplastic transformation has been known for decades [ 2 ]. accumulating evidence shows a correlation between tumor - infiltrating lymphocytes in cancer tissue and favorable prognosis in various malignancies [ 2 ]. in particular, the presence of cd8 + t - cells and the ratio of cd8 + effector t - cells / foxp3 + regulatory t - cells seems to correlate with improved prognosis and long - term survival in solid malignancies such as ovarian, colorectal, and pancreatic cancer ; hepatocellular carcinoma ; malignant melanoma ; and renal cell carcinoma ( rcc ). tumor - infiltrating lymphocytes can be expanded ex vivo and reinfused, inducing durable objective tumor responses in cancers such as melanoma [ 3 ] [ 4 ]. the programmed cell death protein - 1 ( pd - 1 ) receptor - ligand interaction is a major pathway hijacked by tumors to suppress immune control. the normal function of pd - 1, expressed on the cell surface of activated t - cells under healthy conditions, is to down - modulate unwanted or excessive immune responses, including autoimmune reactions. programmed cell death protein - 1 ( encoded by the gene pdcd1 ) is an ig superfamily member related to cd28 and ctla - 4 that has been shown to negatively regulate an



====================================================================================================
CLASS: protocol
CHUNK ID: 60
====================================================================================================
regulatory requirements. clinical supplies sourced locally will be distributed and labeled in accordance with local regulatory requirements. 6. 1 study intervention ( s ) administered the ceftolozane / tazobactam to be used in this study is outlined in table 3. 08wn8y product : mk - 7625a 39 protocol / amendment no. : 036 - 02 mk - 7625a - 036 - 02 final protocol 12 - dec - 2022 table 3 study interventions arm name arm type intervention name intervention type dose formulation unit dose strength ( s ) dosage level ( s ) route of administration regimen / treatment period test product / comparator imp or nimp / axmp sourcing group 1 ( 12 to < 18 years of age [ n = > 6 ] ) experimental ceftolozane / tazobactam drug powder ceftolozane 2 g and tazobactam 1 g ceftolozane 2 g and tazobactam 1 g iv infusion 60 - minute iv infusion ( 10 minutes ) q8h for 8 - 14 days test product imp centrally or locally group 2 ( 7 to < 12 years of age [ n = > 6 ] ) experimental ceftolozane / tazobactam drug powder ceftolozane 2 g and tazobactam 1 g ceftolozane 40 mg / kg and tazobactam 20 mg / kg iv infusion 60 - minute iv infusion ( 10 minutes ) q8h for 8 - 14 days test product imp centrally or locally group 3 ( 2 to < 7 years of age [ n = > 6 ] ) experimental ceftolozane / tazobactam drug powder ceftolozane 2 g and tazobactam 1 g ceftolozane 40 mg / kg and tazobactam 20 mg / kg iv infusion 60 - minute iv infusion ( 10 minutes ) q8h for 8 - 14 days test product imp centrally or locally group 4 ( 3 months to < 2 years of age [ n = > 6 ] ) experimental ceftolozane / tazobactam drug powder ceftolozane 2 g and tazobactam 1 g ceftolozane 40 mg / kg and tazobactam 20 mg / kg iv infusion 60 - minute



====================================================================================================
CLASS: protocol
CHUNK ID: 18
====================================================================================================
figures figure 1 study scheme..................................................................................... 17 figure 2 data collection time windows according to relapse status at recruitment and for remote visits........................................................ 18 substance code : n / a classic - ms ms700568 _ 0026 c o n f i d e n t i a l i n f o r m a t i o n 8 / 84 protocol history version number type version date 1. 0 original protocol 28 jan 2019 2. 0 amended protocol 03 july 2020 protocol version 2. 0 ( 03 - jul - 2020 ) this amendment is nonsubstantial based on the criteria in article 10 ( a ) of directive 2001 / 20 / ec of the european parliament and the council of the european union because it neither significantly impacts the safety or physical / mental integrity of participants nor the scientific value of the study. overall rationale for the amendment the changes implemented in the protocol have been undertaken in order to improve the quality and analytic plans for data collection, by clarifying study endpoints, the time windows for data collection, and the definitions of study subgroups. substance code : n / a classic - ms ms700568 _ 0026 c o n f i d e n t i a l i n f o r m a t i o n 9 / 84 documentation of protocol amendments section # and name description of change brief rationale medical responsible and medical monitor names change in the study physician. study physician has changed since the first protocol was written. section 1. 1, synopsis ; section 3, objectives and endpoints ; section 4. 2, scientific rationale and design ; section 9. 4, statistical analysis updated definition of primary endpoint. new definition to clarify and minimize ambiguity ( per steering committee recommendation ). section



====================================================================================================
CLASS: protocol
CHUNK ID: 51
====================================================================================================
are required by the study protocol, including important sections describing the management of study material. 8. 1 study drug and materials 8. 1. 1 dosage form, manufacturing, packaging, and labeling 8. 1. 1. 1 study drug the study drug igsc, 20 % is a liquid formulation of igg. at least 95 % ( eu specifications ) / 96 % ( us specifications ) of the protein in the study drug is gamma globulin. the product is isotonic and has a ph of 4. 6 to 5. 1 ( diluted at 1 % in saline ). it contains 18. 0 to 22. 0 g of protein per 100 ml and approximately 0. 2 to 0. 3 m glycine. the liquid preparation is clear and colorless or pale yellow or light brown. it contains no preservatives. additional information is provided in the current ib. immune globulin subcutaneous ( human ), 20 % solution ( igsc, 20 % ) will be provided by the sponsor and will be labeled as investigational product ( ip ). 8. 1. 1. 2 packaging immune globulin subcutaneous ( human ), 20 % solution is supplied in single - dose glass vials that nominally contain 4 g and 8 g of protein per vial. changes to sponsor - supplied packaging prior to dosing may not occur without full agreement in advance by the sponsor. 8. 1. 1. 3 labeling labels containing study information and pack identification are applied to the study drug vial and carton. the product will be labeled according to the valid regulatory requirements for clinical studies. 8. 1. 2 storage the investigator has overall responsibility for ensuring that study drug is stored in a secure, limited - access location. limited responsibility may be delegated to the pharmacist or member of the study team, but this delegation must be documented. immune globulin subcutaneous 20 % is distributed or administered by the pharmacist or nominated member of the study team. the pharmacist / nominated team member will enter the subject identifier on the study drug vial / carton labels as they are distributed or administered. property of takeda : for non - commercial use only an



====================================================================================================
CLASS: protocol
CHUNK ID: 84
====================================================================================================
any aes that have an underlying true incidence rate of 5 % or more. if no aes are observed, the upper bound of the 2 - sided 95 % ci for the 0 % ae incidence rate will be 8. 8 %, based on the clopper and pearson method. 9. 2 responsibility for analyses / in - house blinding there is no blinding required for this single arm study. the analysis of the safety data obtained from this study will be the responsibility of the sponsor s clinical biostatistics department. the official, final database will not be locked until medical / scientific review has been performed, protocol deviations have been identified, and data have been declared final and complete. the plasma concentrations at each time point and the primary pk parameters for ceftolozane and tazobactam will be summarized by the sponsor s quantitative pharmacology and pharmacometrics department and the early clinical development statistics department. 9. 3 hypotheses / estimation objectives of the study are stated in section 3. there are no hypotheses to be tested in this study. 9. 4 analysis endpoints 9. 4. 1 safety endpoints safety endpoints include aes ( any aes, any saes, any drug - related aes, any serious and drug - related aes, and aes leading to discontinuation of study intervention ), clinical laboratory tests, and vital sign measurements. the rationale for safety endpoints is provided in section 4. 2. 1. 1, and ecis are defined in section 8. 4. 7. the proportion of subjects who experience aes of elevated laboratory values that are reported as ecis during the study treatment period will be estimated. 9. 4. 2 pk endpoints plasma concentrations for ceftolozane and tazobactam at each time point will be determined and summarized in the csr. plasma concentration data will be used to update the existing ceftolozane and tazobactam pediatric population pk models. due to the sparse pk sampling, the other pk endpoints, including steady state cmax, auc0 - 8, t1 / 2, vd, and cl will be 08wn8y product : mk - 7625a 60

In [15]:
balanced_chunk_df.to_csv(
    "bert_3class_chunk_dataset.csv",
    index=False
)

print("Saved 3-class chunk dataset successfully.")

Saved 3-class chunk dataset successfully.